name: Deploy

on:
  push:
    branches:
      - house-wars

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Yarn install
        run: yarn

      - name: Build
        run: yarn nx build --prod house-wars && yarn nx build --prod house-wars-server

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "deploy[bot]"
          git commit -m "Build changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: house-wars-deploy

#      - name: Deploy
#        uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: house-wars-deploy
#          FOLDER: dist/..
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
